spring:
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 5000
  datasource:
    url: jdbc:mysql://localhost:3307/uav_monitor?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 175245
  jackson:
    time-zone: UTC
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: org.apache.ibatis.type.EnumTypeHandler
  global-config:
    db-config:
      id-type: auto
server:
  port: 8080
security:
  jwt:
    secret: change-me
    expiration-minutes: 120
mqtt:
  broker-url: tcp://localhost:1883
  client-id: uav-backend-${random.uuid}
#  username: backend
#  password: backend
  telemetry-topic: uav/+/telemetry
  command-topic-prefix: uav/
